config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :events, only: [:index, :new]
  
  root 'events#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :events, foreign_key: 'user_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    def index
        @events = Event.all
    end

    def new
        @event = Event.new
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find(params[:id])
    @created_events = @user.events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<header>
<h1>My Bad Ass Events</h1>

<% if user_signed_in? %>
  <%= link_to "New Event", new_event_path, class: "btn btn-primary"%>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger"%>
<% else %>
  <%= link_to 'Sign In', new_user_session_path, class: 'btn btn-primary' %>
  <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-success' %>
<% end %>
</header>



<section class="event-list">
<ul>
  <% @events.each do |event| %>
    <li class="event-card">
      <div class="event-details">
        <h2 class="event-name"><%= event.name %></h2>
        <p class="event-date">Date: <%= event.date.strftime('%B %d, %Y') %></p>
        <p class="event-location">Location: <%= event.location %></p>
      </div>
    </li>
  <% end %>
</ul>
</section>

app/views/events/new.html.erb
<h1>Test test test</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>User Profile: <%= @user.name %></h1>

<h2>Events Created by <%= @user.name %></h2>
<ul>
  <% @created_events.each do |event| %>
    <li>
      <strong><%= event.name %></strong><br>
      Date: <%= event.date.strftime('%B %d, %Y') %><br>
      Location: <%= event.location %>
    </li>
  <% end %>
</ul>